set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

if(DEFINED ENV{RISCV_PREFIX})
    set(TOOLCHAIN_PREFIX $ENV{RISCV_PREFIX})
else()
    set(TOOLCHAIN_PREFIX "riscv64-none-elf-")
endif()

find_program(CMAKE_C_COMPILER   NAMES "${TOOLCHAIN_PREFIX}gcc")
find_program(CMAKE_CXX_COMPILER NAMES "${TOOLCHAIN_PREFIX}g++")
find_program(CMAKE_ASM_COMPILER NAMES "${TOOLCHAIN_PREFIX}gcc")

